testsuite: fix compiler warning about unused variable
Happens on gst-macos-12.3 with --werror with clang 13.1.6
"Apple clang version 13.1.6 (clang-1316.0.21.2)":
../testsuite/memcpy_speed.c:25:23: error: variable 'sum' set but not used