orcarray: Use fabs() instead of abs(), the latter is for integers
orcarray.c:254:15: error: using integer absolute value function 'abs' when
      argument is of floating point type [-Werror,-Wabsolute-value]
          if (abs(a[i] - b[i]) < MIN_NONDENORMAL_D) continue;